name: .NET 8 CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Install dependencies
        run: dotnet restore ./src/LoyaltyProCore

      - name: Build
        run: dotnet build ./src/LoyaltyProCore --no-restore

      - name: Run tests
        run: dotnet test ./src/LoyaltyProCore --no-build --verbosity normal

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'loyaltyprocore'
          slot-name: 'production'
          package: src/LoyaltyProCore
