name: Build and Deploy .NET 8 API

on:
  push:
    branches: ["main"]

env:
  RESOURCE_GROUP: LoyaltyProResources
  WEBAPP_NAME: loyaltyprocore
  ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
  Cloudinary__ApiKey: ${{ secrets.CLOUDINARY_API_KEY }}
  Cloudinary__ApiSecret: ${{ secrets.CLOUDINARY_API_SECRET }}
  JWT__SigningKey: ${{ secrets.JWT_SIGNING_KEY }}
  JWT__Issuer: "loyaltyprocore.azurewebsites.net"
  JWT__Audience: "loyaltyprocore.azurewebsites.net"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.WEBAPP_NAME }}:${{ github.sha }} .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          # resource-group: $RESOURCE_GROUP
          images: "${{ env.WEBAPP_NAME }}:${{ github.sha }}"
          configuration-file: ./azure-app-settings.json
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}
          ASPNETCORE_ENVIRONMENT: "Production"
