name: Deploy to Render

on:
  push:
    branches: [main]

env:
  RENDER_SERVICE_NAME: plum-api
  DOTNET_VERSION: "8.0.x"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run: |
          dotnet restore src/api/api.csproj
          dotnet build src/api/api.csproj -c Release --no-restore

      - name: Test
        run: |
          dotnet test src/api/api.csproj
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.DB_CONNECTION_STRING }}

      - name: Install Render CLI
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g render-cli

      - name: Deploy to Render
        run: |
          render deploy \
            --api-key ${{ secrets.RENDER_API_KEY }} \
            --service ${{ env.RENDER_SERVICE_NAME }} \
            --envVars DATABASE_URL=${{ secrets.DB_CONNECTION_STRING }} \
            --auto-create
