name: Deploy .NET 8 to Azure

on:
  push:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  PROJECT_PATH: src/api/api.csproj
  PUBLISH_PATH: ./publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Setup .NET 8
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      # Build and publish from the correct project path
      - name: Build with dotnet
        run: |
          dotnet restore ${{ env.PROJECT_PATH }}
          dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore
          dotnet publish ${{ env.PROJECT_PATH }} -c Release -o ${{ env.PUBLISH_PATH }}

      # Inject DB connection string (alternative to Azure App Settings)
      - name: Add DB Connection String
        run: |
          echo "{
            \"ConnectionStrings\": {
              \"DefaultConnection\": \"${{ secrets.DB_CONNECTION_STRING }}\"
            },
            \"Logging\": {
              \"LogLevel\": {
                \"Default\": \"Information\",
                \"Microsoft.AspNetCore\": \"Warning\"
              }
            }
          }" > ${{ env.PUBLISH_PATH }}/appsettings.Production.json

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy to Azure (Zip Deploy)
      - name: Run Azure webapp deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.PUBLISH_PATH }}
